name: peft-sam
channels:
    - pytorch
    - nvidia
    - conda-forge
dependencies:
    - imagecodecs
    # This pin is necessary because later nifty versions have import errors on windows.
    - nifty =1.2.1=*_4
    - magicgui
    - micro_sam
    - napari >=0.5.0
    - natsort
    - pip
    - pooch
    - protobuf <5
    - pyqt
    - python-xxhash
    - python-elf >=0.4.8
    - pytorch >=2.4
    - pytorch-cuda>=11.7  # you may need to update the cuda version to match your system
    - segment-anything
    - torchvision
    - torch_em >=0.7.0
    - tqdm
    - timm
    - pip:
        - git+https://github.com/anwai98/tukra.git
        - git+https://github.com/computational-cell-analytics/medico-sam.git
